### ISSUE TITLE
Buildah should work unprivileged

### ISSUE THREAD

**Issue by faust64** [openshift/pipelines-catalog#17]
Hi,

I couldn't help but notice that all samples from this catalog would use Buildah, yet they're also mentioning some `securityContext.privileged: true`.

As far as I know, buildah should work without that configuration. Here's a sample Task I'm using building some NodeJS app image:

```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: node-s2i-build
spec:
  inputs:
    params:
    - name: contextdir
      description: The location of the path to run s2i from
      default: .
      type: string
    - name: fromimage
      description: S2i Base Image
      type: string
      default: image-registry.openshift-image-registry.svc:5000/wsweet-ci/nodejs-wsweet:master
    - name: tlsverify
      description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
      default: "true"
      type: string
    resources:
    - name: source
      targetPath: /
      type: git
  outputs:
    resources:
    - name: image
      type: image
  steps:
  - name: build
    image: image-registry.openshift-image-registry.svc:5000/wsweet-ci/jenkins-agent-node-sonar-wsweet:master
    imagePullPolicy: Always
    command:
    - /bin/sh
    args:
    - -c
    - |
        . /usr/local/bin/set_runtime
        echo NODE_ENV=production >>/env-params/env-file
        echo NO_AUDIT=yep >>/env-params/env-file
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 300m
        memory: 512Mi
    volumeMounts:
    - name: envparams
      mountPath: /env-params
  - name: generate-image-build-assets
    image: quay.io/openshift-pipeline/s2i
    command:
    - s2i
    - build
    - $(inputs.params.contextdir)
    - $(inputs.params.fromimage)
    - --image-scripts-url
    - image:///usr/libexec/s2i
    - --as-dockerfile
    - /gen-source/Dockerfile.gen
    - --environment-file
    - /env-params/env-file
    resources:
      limits:
        cpu: 500m
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 3Gi
    volumeMounts:
    - name: gen-source
      mountPath: /gen-source
    - name: envparams
      mountPath: /env-params
  - name: build-image
    image: quay.io/buildah/stable
    workingdir: /gen-source
    command:
    - buildah
    - bud
    - --storage-driver
    - vfs
    - --tls-verify=$(inputs.params.tlsverify)
    - --layers
    - -f
    - /gen-source/Dockerfile.gen
    - -t
    - $(outputs.resources.image.url)
    - .
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 3Gi
    volumeMounts:
    - name: devfuse
      mountPath: /dev/fuse
    - name: gen-source
      mountPath: /gen-source
    - name: varlibcontainers
      mountPath: /var/lib/containers
  - name: push-image
    image: quay.io/buildah/stable
    command:
    - buildah
    - push
    - --storage-driver
    - vfs
    - --tls-verify=$(inputs.params.tlsverify)
    - $(outputs.resources.image.url)
    - docker://$(outputs.resources.image.url)
    volumeMounts:
    - name: devfuse
      mountPath: /dev/fuse
    - name: varlibcontainers
      mountPath: /var/lib/containers
  volumes:
  - name: varlibcontainers
    emptyDir: {}
  - name: gen-source
    emptyDir: {}
  - name: envparams
    emptyDir: {}
  - name: devfuse
    hostPath:
      path: /dev/fuse
```

As far as I understand, running unprivileged builds with Buildah, we would need to share /dev/fuse from host to build pods, while we should pass buildah with a vfs storage driver option ( see: https://github.com/ocibuilder/ocibuilder/issues/34#issuecomment-545332560 )

Meanwhile, I'm also noticing that we're only listing S2I build examples. Is there any reason not to give some sample alternative to Docker BuildConfigs? FYI, below is another example, still using Buildah, and un-privileged (as opposed to those from tektoncd catalog).

```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: buildah-docker-build
spec:
  inputs:
    params:
    - name: builderimage
      description: The location of the buildah builder image.
      default: quay.io/buildah/stable
      type: string
    - name: dockerfile
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
      type: string
    - name: fromimage
      description: Forces FROM in Dockerfile.
      default: ""
      type: string
    - name: tlsverify
      description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
      default: "true"
      type: string
    resources:
    - name: source
      type: git
  outputs:
    resources:
    - name: image
      type: image
  steps:
  - name: patch-from
    image: $(inputs.params.builderimage)
    workingDir: /workspace/source
    command:
    - /bin/bash
    - -c
    - if test "$(inputs.params.fromimage)"; then sed -i "s|^[ ]*FROM[ ]*[^ ]*$|FROM $(inputs.params.fromimage)|" "/workspace/source/$(inputs.params.dockerfile)"; fi
  - name: build
    image: $(inputs.params.builderimage)
    workingDir: /workspace/source
    env:
    - name: DO_UPGRADE
      value: "true"
    command:
    - buildah
    - bud
    - --storage-driver
    - vfs
    - --tls-verify=$(inputs.params.tlsverify)
    - --layers
    - -f
    - $(inputs.params.dockerfile)
    - -t
    - $(outputs.resources.image.url)
    - .
    resources:
      limits:
        cpu: 700m
        memory: 3Gi
      requests:
        cpu: 500m
        memory: 2Gi
    volumeMounts:
    - name: devfuse
      mountPath: /dev/fuse
    - name: varlibcontainers
      mountPath: /var/lib/containers
  - name: push
    image: $(inputs.params.builderimage)
    workingDir: /workspace/source
    command:
    - buildah
    - push
    - --storage-driver
    - vfs
    - --tls-verify=$(inputs.params.tlsverify)
    - $(outputs.resources.image.url)
    - docker://$(outputs.resources.image.url)
    resources:
      limits:
        cpu: 500m
        memory: 3Gi
      requests:
        cpu: 500m
        memory: 2Gi
    volumeMounts:
    - name: devfuse
      mountPath: /dev/fuse
    - name: varlibcontainers
      mountPath: /var/lib/containers
  volumes:
  - hostPath:
      path: /dev/fuse
    name: devfuse
  - name: varlibcontainers
    emptyDir: {}
```

If you're interested, I could submit a PR patching existing samples and adding one for non-S2I builds.
