### ISSUE TITLE
s2i README docs mix different workspace names

### ISSUE THREAD

**Issue by tux-o-matic** [openshift/pipelines-catalog#71]
The *README* files re-used across the repo don't stick to the same workspace name.
Anyone trying to create pipelines based on those example would end up with a PVC that is not getting mounted by the containers running *Tasks*.
In the *Pipeline* the workspace named `shared-workspace`is used but for the *PipelineRun* a PVC claim for a workspace named `shared-data`is declared.

For example the [Python3 s2i Task](https://github.com/openshift/pipelines-catalog/blob/master/task/s2i-python-3/0.1/README.md) but applies to the other *Tasks README*:
```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: s2i-python-3-pipeline
spec:
  params:
    - name: IMAGE
      description: Location of the repo where image has to be pushed
      type: string
  workspaces:
    - name: shared-workspace
```
And so on for all workspace reference in the *Pipeline* example.

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: s2i-python-3-pipelinerun
spec:
  # Use service account with git and image repo credentials
  serviceAccountName: pipeline
  pipelineRunRef:
    name: s2i-python-3-pipeline
  params:
  - name: IMAGE
    value: quay.io/my-repo/my-image-name
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
```
