### ISSUE TITLE
Should use proper RBAC to grant the privileged SCC

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/pipelines-catalog#9]
Current instructions on many tasks say:

> Creating a ServiceAccount
> S2I builds an image and pushes it to the destination registry which is defined as a parameter. The image needs proper credentials to be authenticated by the remote container registry. These credentials can be provided through a serviceaccount. See Authentication for further details.
> 
> If you run on OpenShift, you also need to allow the service account to run privileged containers. Due to security considerations OpenShift does not allow containers to run as privileged containers by default.
> 
> Run the following in order to create a service account named pipelines on OpenShift and allow it to run privileged containers:
> 
> ```
> oc create serviceaccount pipeline
> oc adm policy add-scc-to-user privileged -z pipeline
> oc adm policy add-role-to-user edit -z pipeline
> ```

This should be changed to use proper RBAC, as RBAC should be the preferred way to consume SCCs and not modifying the SCC itself.

Create this clusterRole (once on the platform). Ideally there should be this role deployed by default on an OpenShift platform.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: "Role-Based Access to SCCs for Tekton Pipelines privileged tasks"
  name: pipelines-privileged-user
rules:
- apiGroups:
  - security.openshift.io 
  resources:
  - securitycontextconstraints 
  verbs:
  - use
  resourceNames:
  - privileged
```

This ClusterRole allows any user with a RoleBinding to it to use the privileged SCC.

Create the SA via CLI or via `oc create`:

```
kind: ServiceAccount,
apiVersion: v1
metadata: 
  name: pipelines
```

Then create a RoleBinding to grant this SA to use the ClusterRole that allows it to use the privileged SCC.

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipelines-privileged-user
subjects
- kind: ServiceAccount
   name: pipelines
roleRef: 
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: pipelines-privileged-user
```
